<?php

namespace backend\controllers;

use common\models\HistoryEvents;
use common\models\HistoryGallery;
use Yii;
use common\models\History;
use common\models\HistorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * HistoryController implements the CRUD actions for History model.
 */
class HistoryEventsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                 //   'delete' => ['POST'],
                ],
            ],
        ];
    }
    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
            header('location:/admin/login');
            exit;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    /**
     * Lists all History models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new HistorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new History model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new HistoryEvents();

        if ($model->updateModel(true)) {
            return $this->redirect(['update', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'gallery' => false,

        ]);
    }

    /**
     * Updates an existing History model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->updateModel()) {
            return $this->redirect(['update', 'id' => $model->id]);
        }

        if( ! $gallery = HistoryGallery::find()->where(['history_id'=>$model->id])->all()){
            $gallery = false;
        }


        return $this->render('update', [
            'model' => $model,
            'gallery' => $gallery,
        ]);
    }

    /**
     * Deletes an existing History model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $history_id = $model->history_id;
        $model->delete();

        return $this->redirect(['/history/update','id'=>$history_id]);
    }

    /**
     * Finds the History model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return History the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if ( ( $model = HistoryEvents::findOne($id) ) !== null ) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    // удаление изображения из галереи
    public function actionDeleteGalleryItem()
    {
        $id = (int)Yii::$app->request->post('id');
        if($gallery = HistoryGallery::findOne($id)){
            $p_id = $gallery->history_id;
            $path = Yii::getAlias("@frontend/web/uploads/history-events/" . $p_id . '/gallery/' );
            @unlink($path . $gallery->image);
            $path = Yii::getAlias("@frontend/web/uploads/history-events/" . $p_id . '/gallery/thumb/' );
            @unlink($path . $gallery->image);

            $gallery->delete();

            echo json_encode(['status'=>1]);
        }else{
            echo json_encode(['status'=>0]);
        }

        exit;
    }
}
