<?php

namespace backend\controllers;

use Yii;
use common\models\NewsGallery;
use common\models\NewsGallerySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsGalleryController implements the CRUD actions for NewsGallery model.
 */
class NewsGalleryController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                //    'delete' => ['post'],
                ],
            ],
        ];
    }
    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
            header('location:/admin/login');
            exit;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    /**
     * Lists all NewsGallery models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NewsGallerySearch();
        $dataProvider = $searchModel->search( Yii::$app->request->queryParams );

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new NewsGallery model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new NewsGallery();

        if ( $model->updateModel(true) ) {
            return $this->redirect(['update', 'id' => $model->id]);

        }else{
            return $this->render('create', [
                'model' => $model,
            ]);

        }
    }

    /**
     * Updates an existing NewsGallery model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->updateModel()) {
            return $this->redirect(['update', 'id' => $model->id]);

        }else{
            return $this->render('update', [
                'model' => $model,
            ]);

        }
    }

    /**
     * Deletes an existing NewsGallery model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $ref = Yii::$app->request->referrer;

        if( $gallery = $this->findModel($id) ) {
            $path = Yii::getAlias("@frontend/web/uploads/news-gallery/" . $id . '/' );
            @unlink($path . $gallery->image);

            $path = Yii::getAlias("@frontend/web/uploads/news-gallery/" . $id . '/thumb/' );
            @unlink($path . $gallery->image);

            $path = Yii::getAlias("@frontend/web/uploads/news-gallery/" . $id . '/thumb/' );
            @rmdir($path);

            $path = Yii::getAlias("@frontend/web/uploads/news-gallery/" . $id  );
            @rmdir($path);

            $gallery->delete();

        }

        return $this->redirect($ref);
    }

    /**
     * Finds the NewsGallery model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return NewsGallery the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = NewsGallery::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}
