<?php
namespace frontend\controllers;

use Codeception\PHPUnit\Constraint\Page;
use common\helpers\ListHelper;
use common\models\Address;
use common\models\Brands;
use common\models\Categories;
use common\models\Colors;
use common\models\Comments;
use common\models\Favorites;
use common\models\Pages;
use common\models\Products;
use common\models\Styles;
use common\models\Transport;
use common\models\Videos;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use yii\data\Pagination;
use yii\web\NotFoundHttpException;


/**
 * Site controller
 */
class TransportController extends Controller
{

    private $lang = 'ru';

    public function beforeAction($action)
    {
        $lang = Yii::$app->session->get('lang');
        if( $lang =='' ) $lang = 'ru';
        $this->lang = $lang;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {

        return $this->render('index',[
            'lang' => $this->lang,
        ]);
    }


    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionBus()
    {

        if(!$transport=Transport::find()->where(['status'=>1,'type'=>0])->orderBy('pos  DESC')->all()){
            $transport=false;
        }
        //echo 'bus'; exit;
        //print_r($transport);

        return $this->render('bus',[
            'transport'=> $transport,
            'lang' => $this->lang,
        ]);
    }
    public function actionTrucks()
    {
        if(!$transport=Transport::find()->where(['status'=>1,'type'=>1])->orderBy('pos  DESC')->all()){
            $transport=false;
        }

        return $this->render('trucks',[
            'transport'=> $transport,
            'lang' => $this->lang,
        ]);
    }

    public function actionSpecial()
    {
        if(!$transport=Transport::find()->where(['status'=>1,'type'=>2])->orderBy('pos  DESC')->all()){
            $transport=false;
        }

        return $this->render('special',[
            'transport'=> $transport,
            'lang' => $this->lang,
        ]);
    }

    public function actionItem($id)
    {
        if($transport=Transport::find()->with('gallery')->where(['status'=>1,'id'=>$id])->one()){
            $data = json_decode($transport->data,true);
            $data = $data['complect'];

        }else{
            $transport=false;
            $data = false;

        }

        return $this->render('item',[
            'transport'=> $transport,
            'data' => $data,
            'lang' => $this->lang,

        ]);
    }



}