<?php

namespace frontend\controllers;

use common\models\Address;
use common\models\Brands;
use common\models\Favorites;
use common\models\IrbisGallery;
use common\models\PikupsPage;
use common\models\Styles;
use common\models\TabPanel;
use common\models\Transport;
use common\models\Videos;
use Yii;
use yii\helpers\VarDumper;
use yii\web\Controller;


/**
 * Site controller
 */

const STATUS_WAIT = NUll;
const STATUS_ACTIVE = 10;
class TransportController extends Controller
{

    private $lang = 'ru';

    public function beforeAction($action)
    {
        $lang = Yii::$app->session->get('lang');
        if ($lang == '') $lang = 'ru';
        $this->lang = $lang;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {

        return $this->render('index', [
            'lang' => $this->lang,
        ]);
    }


    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionBus()
    {

        if (!$transport = Transport::find()->where(['status' => 1, 'type' => 0])->orderBy('pos  DESC')->all()) {
            $transport = false;
        }
        //echo 'bus'; exit;
        //print_r($transport);

        return $this->render('bus', [
            'transport' => $transport,
            'lang' => $this->lang,
        ]);
    }

    public function actionPickups()
    {

        if (!$transport = Transport::find()->where(['status' => 1, 'type' => 3])->orderBy('pos  DESC')->all()) {
            $transport = false;
        }
        //echo 'bus'; exit;
        //print_r($transport);

        return $this->render('pickups', [
            'transport' => $transport,
            'lang' => $this->lang,
        ]);
    }

    public function actionTrucks()
    {
        if (!$transport = Transport::find()->where(['status' => 1, 'type' => 1])->orderBy('pos  DESC')->all()) {
            $transport = false;
        }

        return $this->render('trucks', [
            'transport' => $transport,
            'lang' => $this->lang,
        ]);
    }

    public function actionSpecial()
    {
        if (!$transport = Transport::find()->where(['status' => 1, 'type' => 2])->orderBy('pos  DESC')->all()) {
            $transport = false;
        }

        return $this->render('special', [
            'transport' => $transport,
            'lang' => $this->lang,
        ]);
    }

    public function actionItem($id)
    {
        if ($transport = Transport::find()->with('gallery')->where(['status' => 1, 'id' => $id])->one()) {
            $data = json_decode($transport->data, true);
            $data = $data['complect'];

        } else {
            $transport = false;
            $data = false;

        }

        return $this->render('item', [
            'transport' => $transport,
            'data' => $data,
            'lang' => $this->lang,

        ]);
    }

    public function actionPickupitem($id)
    {
        $tabpanelactive = TabPanel::find()->where(['status' => 1])->andWhere(['transport_id' => $id])->one();
        $tabpanel = TabPanel::find()->where(['status' => 0])->andWhere(['transport_id' => $id])->all();
        $pikups = PikupsPage::find()->where(['transport_id' => $id])->one();
        if ($transport = Transport::find()->with('gallery')->where(['status' => 1, 'id' => $id])->one()) {
            $data = json_decode($transport->data, true);
            $data = $data['complect'];

        } else {
            $transport = false;
            $data = false;

        };
        return $this->render('pickupitem', [
            'transport' => $transport,
            'data' => $data,
            'lang' => $this->lang,
            'pikups' => $pikups,
            'tabpanelactive' => $tabpanelactive,
            'tabpanel' => $tabpanel,
        ]);
    }

    public function actionGalleryitem($id)
    {
        $gallery = IrbisGallery::find()->where(['transport_id' => $id])->all();

        return $this->render('galleryitem', [
            'gallery' => $gallery,
            'lang' => $this->lang,
        ]);
    }

    public function actionInterior($id)
    {
        if ($transport = Transport::find()->with('gallery')->where(['status' => 1, 'id' => $id])->one()) {
            $data = json_decode($transport->data, true);
            $data = $data['complect'];

        } else {
            $transport = false;
            $data = false;

        }
        return $this->render('interior', [
            'transport' => $transport,
            'data' => $data,
            'lang' => $this->lang,
        ]);
    }

    public function actionIrbis()
    {

        return $this->renderFile('@frontend/views/transport/index.html', [

        ]);
    }



    public function actionSearch($get,$get1,$get2)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
//        $get = Yii::$app->request->post('destination');
//        $get1 = Yii::$app->request->post('passengers');
//        $get2 = Yii::$app->request->post('back');

        if ($get1 == 15) {
            $transport = Transport::find()->andFilterWhere(['type' => 0])
                ->andFilterWhere(['between', 'count', 15, 45])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get2])
                ->andFilterWhere(['like', 'title_ru', $get])->all();
            return [
                'transport' => $transport,
                'lang' => $this->lang,
            ];

        } elseif ($_POST['passengers'] == 46) {
            $transport = Transport::find()->andFilterWhere(['type' => 0])
                ->andFilterWhere(['between', 'count', 46, 80])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get2])
                ->andFilterWhere(['like', 'title_ru', $get])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);

        } elseif ($_POST['passengers'] == 81) {
            $transport = Transport::find()->andFilterWhere(['type' => 0])
                ->andFilterWhere(['between', 'count', 81, 116])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get2])
                ->andFilterWhere(['like', 'data', $get])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        } elseif ($_POST['passengers'] == 116) {
            $transport = Transport::find()->andFilterWhere(['type' => 0])
                ->andFilterWhere(['between', 'count', 116, 500])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get2])
                ->andFilterWhere(['like', 'data', $get])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        }

    }


    public function actionSearch1()
    {
        $get = Yii::$app->request->post('mass');
        $get2 = Yii::$app->request->post('trucks');
        $get3 = Yii::$app->request->post('front');
        $get4 = Yii::$app->request->post('gears');

        if ($get2 == 4) {
            $transport = Transport::find()->andFilterWhere(['type' => 1])
                ->andFilterWhere(['between', 'trucks', 1000, 4000])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['tip_kuzov' => $get])
                ->andFilterWhere(['special' => $get3])
                ->andFilterWhere(['like', 'data', $get4])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);

        } elseif ($get2 == 8) {
            $transport = Transport::find()->andFilterWhere(['type' => 1])
                ->andFilterWhere(['between', 'trucks', 4000, 8000])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get])
                ->andFilterWhere(['special' => $get3])
                ->andFilterWhere(['like', 'data', $get4])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        } elseif ($get2 == 12) {
            $transport = Transport::find()->andFilterWhere(['type' => 1])
                ->andFilterWhere(['between', 'trucks', 8000, 16000])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get])
                ->andFilterWhere(['special' => $get3])
                ->andFilterWhere(['like', 'data', $get4])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        } elseif ($get2 == 16) {
            $transport = Transport::find()->andFilterWhere(['type' => 1])
                ->andFilterWhere(['between', 'trucks', 16000, 20000])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get])
                ->andFilterWhere(['special' => $get3])
                ->andFilterWhere(['like', 'data', $get4])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        } elseif ($get2 == 20) {
            $transport = Transport::find()->andFilterWhere(['type' => 1])
                ->andFilterWhere(['between', 'trucks', 20000, 25000])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get])
                ->andFilterWhere(['special' => $get3])
                ->andFilterWhere(['like', 'data', $get4])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        } elseif ($get2 == 25) {
            $transport = Transport::find()->andFilterWhere(['type' => 1])
                ->andFilterWhere(['between', 'trucks', 25000, 100000])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['special' => $get])
                ->andFilterWhere(['special' => $get3])
                ->andFilterWhere(['like', 'data', $get4])->all();
            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        } else {
            return $this->render('index', [
//                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        }
    }

    public function actionSearch2()
    {
        $data = Yii::$app->request->post('auto');

        if ($data) {
            $other = 'other';
            $get = $_POST['auto'];
            if ($data == 8) {
                $transport = Transport::find()->Where(['tip_kuzov' =>  '9'])
                    ->andWhere(['status' => 1])
                    ->andWhere(['type' => 2])->all();
                return $this->render('index', [
                    'transport' => $transport,
                    'lang' => $this->lang,
                ]);
            } else {
                $transport = Transport::find()->Where(['tip_kuzov' =>  $get])
                    ->andWhere(['status' => 1])
                    ->andWhere(['type' => 2])->all();
                return $this->render('index', [
                    'transport' => $transport,
                    'lang' => $this->lang,
                ]);
            }

        } else {
            return $this->render('index', [
                'lang' => $this->lang,
            ]);
        }
    }

    public function actionSearch3()
    {
        $data = Yii::$app->request->post('gearbox');
        $data1 = Yii::$app->request->post('gears');
        $data2 = Yii::$app->request->post('volume');
        $data3 = Yii::$app->request->post('count');

        if ($data || $data1 || $data2 || $data3) {
            $transport = Transport::find()->andFilterWhere(['type' => 3])
                ->andFilterWhere(['status' => 1])
                ->andFilterWhere(['auto_mex' => $data])
                ->andFilterWhere(['like', 'data', $data1])
                ->andFilterWhere(['like', 'data', $data2])
                ->andFilterWhere(['doors' => $data3])->all();

            return $this->render('index', [
                'transport' => $transport,
                'lang' => $this->lang,
            ]);
        } else {
            return $this->render('index', [
                'lang' => $this->lang,
            ]);
        }
    }

}