<?php

namespace common\models;

use Yii;
use common\helpers\TextHelper;
use common\models\Images;

use yii\imagine\Image;
use yii\web\UploadedFile;


/**
 * This is the model class for table "career_info".
 *
 * @property integer $id
    
 * @property string $title_ru
    
 * @property string $title_uz
    
 * @property string $title_en
    
 * @property string $preview_img
    
 * @property string $text_ru
    
 * @property string $text_uz
    
 * @property string $text_en
    
 * @property integer $status
    
 */
class CareerInfo extends \yii\db\ActiveRecord
{

    public $image;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'career_info';
    }


    public function afterDelete()
    {
        if ($this->preview_img !== null && !empty($this->preview_img)) {
            unlink(Yii::getAlias('@frontend').'/web/uploads/career/info/' . $this->preview_img);
        }
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text_ru', 'text_uz', 'text_en'], 'string'],
            [['status'], 'integer'],
            [['title_ru', 'title_uz', 'title_en', 'preview_img'], 'string', 'max' => 255],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif, bmp']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title_ru' => 'Заголовок Ru',
            'title_uz' => 'Заголовок Uz',
            'title_en' => 'Заголовок En',
            'text_ru' => 'Текст Ru',
            'text_uz' => 'Текст Uz',
            'text_en' => 'Текст En',
            'status' => 'Статус',
            'preview_img' => 'Изображение превью',
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
            $name = Yii::$app->security->generateRandomString(10) . '.' . $this->image->extension;

            if ($this->preview_img !== null && !empty($this->preview_img)) {
                unlink(Yii::getAlias('@frontend').'/web/uploads/career/info/' . $this->preview_img);
            }
            $this->preview_img = $name;
            $this->image->saveAs(Yii::getAlias('@frontend').'/web/uploads/career/info/' . $name);
            return true;
        } else {
            return false;
        }
    }

}
