<?php

namespace common\models;

use Yii;
use yii\imagine\Image;
use yii\web\UploadedFile;

/**
 * This is the model class for table "history".
 *
 * @property int $id
 * @property int $year
 * @property int $status
 */
class History extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'history';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['year', 'status'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'year' => 'Год',
            'status' => 'Статус',
        ];
    }
    public function getEvents()
    {
        return $this->hasMany(HistoryEvents::className(), ['history_id'=>'id'])
            ->with('gallery')
            ->where(['status'=>1])
            ->orderBy('date DESC'); // TODO: Change the autogenerated stub
    }
    public function getEventsgroup()
    {
        return $this->hasMany(HistoryEvents::className(), ['history_id'=>'id'])
            //->with('gallery')
            ->select('id,history_id,date')
            ->where(['status'=>1])
            ->orderBy('date ASC')
            ->groupBy('date'); // TODO: Change the autogenerated stub
    }


    public function updateModel($is_new=false)
    {

        $post = Yii::$app->request->post();

        if($this->load($post) ) {

            if($is_new) $this->save(); // чтобы получить model->id для фото

           // echo '<pre>';print_r([$post,$_FILES]); exit;


            if( !$this->save() ){
                Yii::$app->session->setFlash('info-error','Ошибка при сохранении!');
                print_r($this->getErrors());
                exit;

                return true;
            }

            // print_r($_FILES); exit;
            try {

                // изображения галереи
                if( $files = UploadedFile::getInstances($this, 'tmp_gallery_images' ) ) {

                    $deleted_files = explode(';', $post['delete_gallery_files']);

                    $i = 0;
                    foreach ($files as $file) {
                        $i++;
                        if( ! preg_match('/image/',$file->type) ) continue; // пропустить если не картинка

                        // данный файл удален пользователем
                        if (in_array($i, $deleted_files)) continue;

                        $fid = time() + $i;
                        $fname = $fid . '.' . $file->extension; // preg_replace('/tmp_/','',$image); //  убрать префикс

                        $path_main = Yii::getAlias("@frontend/web/uploads/history/{$this->id}");
                        $path = Yii::getAlias("@frontend/web/uploads/history/{$this->id}/gallery/");

                        if (!is_dir($path_main)) @mkdir($path_main);
                        if (!is_dir($path)) @mkdir($path);
                        if(!is_dir($path.'thumb')) @mkdir($path .'thumb');

                        // основная картинка - оригинал
                        $file->saveAs($path . $fname); // . $file->extension);

                        $gallery = new HistoryGallery();
                        $gallery->image = $fname;
                        $gallery->history_id = $this->id;
                        $gallery->save();

                        $filepath = $path . $fname ;

                        // эскиз
                        Image::thumbnail($filepath, 80, 100)
                            ->save($path . 'thumb/' . $fname , ['quality' => 100]);

                        // эскиз
                        Image::thumbnail($filepath, 1200, 740)
                            ->save($path . $fname , ['quality' => 100]);

                    }
                }

            }catch (Exception $e) {
                print_r($e);
                exit;
            }


            if( !$this->save() ){
                Yii::$app->session->setFlash('info-error','Ошибка при сохранении!');
                print_r($this->getErrors());
                exit;

                return true;
            }

            Yii::$app->session->setFlash('info-success','Запись успешно добавлена!');

            return true;
        }
        return false;

    }

}
