<?php

namespace common\models;

use common\helpers\TextHelper;
use Yii;


/**
 * This is the model class for table "irbis_gallery".
 *
 * @property integer $id
 * @property string $photo
 * @property string $status
 * @property integer $transport_id
 */
class IrbisGallery extends \yii\db\ActiveRecord
{
    public $image;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'irbis_gallery';
    }

    public function afterDelete()
    {
        if ($this->photo !== null && !empty($this->photo)) {
            unlink(Yii::getAlias('@frontend') . '/web/uploads/irbis-gallery/' . $this->photo);
        }
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['transport_id'], 'required'],
            [['photo', 'status'], 'string', 'max' => 255],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif, bmp']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'photo' => Yii::t('app', 'Photo'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    public function getTransport()
    {
        return $this->hasOne(Transport::className(), ['id' => 'transport_id']);
    }

    public function updateModel($new = false)
    {

        $post = Yii::$app->request->post();

        if ($this->load($post)) {

            if ($new) { // если создается только один раз при создании
                //$this->date = time();
            }

            if (!$this->save()) {
                Yii::$app->session->setFlash('info-error', 'Ошибка при сохранении!');
                print_r($this->getErrors());
                exit;

                return true;
            }
        }
    }

    public function upload()
    {
        if ($this->validate()) {
            $name = Yii::$app->security->generateRandomString(10) . '.' . $this->image->extension;

            if ($this->photo !== null && !empty($this->photo)) {
                unlink(Yii::getAlias('@frontend') . '/web/uploads/irbis-gallery/' . $this->photo);
            }
            $this->photo = $name;
            $this->image->saveAs(Yii::getAlias('@frontend') . '/web/uploads/irbis-gallery/' . $name);
            return true;
        } else {
            return false;
        }
    }

}
