<?php

namespace common\models;

use Yii;
use common\helpers\TextHelper;
use common\models\Images;

use yii\imagine\Image;
use yii\web\UploadedFile;


/**
 * This is the model class for table "tab_panel".
 *
 * @property integer $id
    
 * @property string $photo
    
 * @property string $title_ru
    
 * @property string $title_uz
    
 * @property string $title_en
    
 * @property string $content_ru
    
 * @property string $content_uz

 *   @property string $status

 *   @property integer $transport_id

 * @property string $content_en
    
 */
class TabPanel extends \yii\db\ActiveRecord
{
    public $image;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tab_panel';
    }

    public function afterDelete()
    {
        if ($this->photo !== null && !empty($this->photo)) {
            unlink(Yii::getAlias('@frontend').'/web/uploads/tab-panel/' . $this->photo);
        }
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title_ru', 'title_uz', 'title_en', 'content_ru', 'content_uz', 'content_en','transport_id'], 'required'],
            [['content_ru', 'content_uz', 'content_en'], 'string'],
            [['photo', 'title_ru', 'title_uz', 'title_en' , 'status'], 'string', 'max' => 255],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg, gif, bmp']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'status' => 'Статус',
            'id' => Yii::t('app', 'ID'),
            'photo' => Yii::t('app', 'Photo'),
            'title_ru' => Yii::t('app', 'Title Ru'),
            'title_uz' => Yii::t('app', 'Title Uz'),
            'title_en' => Yii::t('app', 'Title En'),
            'content_ru' => Yii::t('app', 'Content Ru'),
            'content_uz' => Yii::t('app', 'Content Uz'),
            'content_en' => Yii::t('app', 'Content En'),
        ];
    }

    public function getTransport(){
        return $this->hasOne(Transport::className(),['id'=>'transport_id']);
    }

    public function updateModel($new=false){

        $post = Yii::$app->request->post();

        if($this->load($post) ) {

            if( $new ){ // если создается только один раз при создании
                //$this->date = time();
            }

                        if(isset($this->link)){
                if( $this->link == '' || isset($post['TabPanel']['title']) ) {
                    $this->link = TextHelper::Transliterate( $post['TabPanel']['title'] );
                }
            }


            if( !$this->save() ){
                Yii::$app->session->setFlash('info-error','Ошибка при сохранении!');
                print_r($this->getErrors());
                exit;

                return true;
            }



            Yii::$app->session->setFlash('info-success',' успешно сохранена!');

            return true;
        }
        return false;

    }
    public function upload()
    {
        if ($this->validate()) {
            $name = Yii::$app->security->generateRandomString(10) . '.' . $this->image->extension;

            if ($this->photo !== null && !empty($this->photo)) {
                unlink(Yii::getAlias('@frontend').'/web/uploads/tab-panel/' . $this->photo);
            }
            $this->photo = $name;
            $this->image->saveAs(Yii::getAlias('@frontend').'/web/uploads/tab-panel/' . $name);
            return true;
        } else {
            return false;
        }
    }

}
