<?php

namespace common\models;

use Yii;
use common\helpers\TextHelper;
use common\models\Images;

use yii\imagine\Image;
use yii\web\UploadedFile;


/**
 * This is the model class for table "vacancy_request".
 *
 * @property integer $id
    
 * @property string $firstname
    
 * @property string $secondname
    
 * @property string $thirdname
    
 * @property string $phone
    
 * @property string $email
    
 * @property string $resume_file
    
 * @property string $created_at
    
 * @property string $updated_at

 * @property integer $vacancy_id

 * @property integer $status
    
 */
class VacancyRequest extends \yii\db\ActiveRecord
{
    public $file;

    const STATUS_WAIT = 0;
    const STATUS_ACTIVE = 10;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vacancy_request';
    }


    public function afterDelete()
    {
        if ($this->resume_file !== null && !empty($this->resume_file)) {
            unlink(Yii::getAlias('@backend').'/web/uploads/resume/' . $this->resume_file);
        }
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['firstname', 'secondname', 'thirdname', 'phone', 'email', 'vacancy_id'], 'required'],
            [['created_at', 'updated_at'], 'safe'],
            [['status'], 'integer'],
            [['firstname', 'secondname', 'thirdname', 'phone'], 'string', 'max' => 50],
            [['email'], 'string', 'max' => 100],
            [['resume_file'], 'string', 'max' => 255],
            [['file'], 'file', 'skipOnEmpty' => false, 'extensions' => 'doc, docx, xls, xlsx, pdf']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'firstname' => 'Имя',
            'secondname' => 'Фамилия',
            'thirdname' => 'Отчество',
            'phone' => 'Номер телефона',
            'email' => 'E-mail',
            'resume_file' => 'Резюме',
            'file' => 'Резюме',
            'vacancy_id' => 'Vacancy Id',
            'created_at' => 'Отправлен',
            'updated_at' => 'Изменен',
            'status' => 'Статус',
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
            $name = $this->file->baseName . '_' . Yii::$app->security->generateRandomString(5) . '.' . $this->file->extension;

            if ($this->resume_file !== null && !empty($this->resume_file)) {
                unlink(Yii::getAlias('@backend').'/web/uploads/resume/' . $this->resume_file);
            }
            $this->resume_file = $name;
            $this->file->saveAs(Yii::getAlias('@backend').'/web/uploads/resume/' . $name);
            return true;
        } else {
            return false;
        }
    }

    public function isWait()
    {
        return $this->status === self::STATUS_WAIT;
    }
    public function isActive()
    {
        return $this->status === self::STATUS_ACTIVE;
    }
    public function getVacancy()
    {
        return $this->hasOne(Vacancy::className(), ['id' => 'vacancy_id']);
    }


}
